In [380]:
import torch
import numpy as np
torch.__version__

'2.4.1+cpu'

# 0D Tensor (Scalar)

In [90]:
scalar = torch.tensor(-5)
scalar
scalar.item()

tensor(-5)

-5

In [48]:
scalar.dim()
scalar.ndim

0

0

In [45]:
scalar.size()
scalar.shape

torch.Size([])

torch.Size([])

In [91]:
scalar.dtype

torch.int64

# 1D Tensor (Vector)

In [92]:
vector = torch.tensor([5, 4, 7])
vector

tensor([5, 4, 7])

In [93]:
vector.ndim
vector.shape
vector.dtype

1

torch.Size([3])

torch.int64

In [75]:
len(vector)
vector.numel()

3

3

In [77]:
vector.sum()
vector.float().mean()

tensor(16)

tensor(5.3333)

In [78]:
# L2 norm (Euclidean length)
vector.float().norm()
(vector**2).sum().sqrt()

tensor(9.4868)

tensor(9.4868)

# 2D Tensor (Matrix)

In [94]:
matrix = torch.tensor([
    [7, 8],
    [9, 5]
])
matrix
matrix.ndim
matrix.shape

tensor([[7, 8],
        [9, 5]])

2

torch.Size([2, 2])

In [117]:
len(vector)
vector.numel()

3

3

In [105]:
matrix.float().det()  # Determinant
matrix.trace()  # Sum of diagonals
matrix.float().norm()  # Frobenius norm

tensor(-37.)

tensor(12)

tensor(14.7986)

# Higher-Order Tensors (Rank ≥ 3)

In [113]:
tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
tensor.ndim
tensor.shape

3

torch.Size([1, 3, 3])

In [118]:
len(tensor)
tensor.numel()

1

9

# Useful Tensor Initializations

In [124]:
torch.zeros(size=(2, 2))
torch.ones(size=(2, 2))
torch.eye(2)

tensor([[0., 0.],
        [0., 0.]])

tensor([[1., 1.],
        [1., 1.]])

tensor([[1., 0.],
        [0., 1.]])

In [147]:
torch.rand(size=(2, 2))
torch.randint(1, 5, size=(2, 10))

tensor([[0.4821, 0.2936],
        [0.0204, 0.0496]])

tensor([[4, 3, 4, 3, 2, 2, 2, 4, 3, 2],
        [2, 2, 4, 2, 1, 1, 1, 4, 1, 3]])

In [154]:
torch.arange(1, 10, 2)
torch.linspace(1, 2, 5)

tensor([1, 3, 5, 7, 9])

tensor([1.0000, 1.2500, 1.5000, 1.7500, 2.0000])

In [157]:
# Tensor of zeros similar to another tensor
torch.zeros_like(matrix)

tensor([[0, 0],
        [0, 0]])

# Tensor datatypes

In [162]:
torch.tensor([3.0, 6.0, 9.0]).dtype
torch.tensor([3, 6, 9]).dtype

torch.float32

torch.int64

In [171]:
torch.tensor([3, 6, 9], dtype=float).dtype
torch.tensor([3, 6, 9], dtype=int).dtype

torch.float64

torch.int64

In [176]:
torch.tensor([3, 6, 9], dtype=torch.float32).dtype
torch.tensor([3, 6, 9], dtype=torch.float16).dtype
torch.tensor([3, 6, 9], dtype=torch.int32).dtype

torch.float32

torch.float16

torch.int32

In [392]:
tensor = torch.tensor([3, 6, 9])
tensor.dtype

tensor.type(torch.float)  # Can change the type like this
tensor.float()  # Or like this

torch.int64

tensor([3., 6., 9.])

tensor([3., 6., 9.])

# Basic operations

In [195]:
tensor = torch.tensor([2, 3, 5])
tensor + 10
tensor / 2
tensor // 2

tensor([12, 13, 15])

tensor([1.0000, 1.5000, 2.5000])

tensor([1, 1, 2])

In [196]:
tensor % 2
tensor % 2 == 0

tensor([0, 1, 1])

tensor([ True, False, False])

In [198]:
tensor ** 2
tensor.sqrt()

tensor([ 4,  9, 25])

tensor([1.4142, 1.7321, 2.2361])

In [213]:
torch.tensor([10, 20, 30]) + torch.tensor([1, 2, 3])
torch.tensor([10, 20, 30]) / torch.tensor([2, 2, 3])

tensor([11, 22, 33])

tensor([ 5., 10., 10.])

In [311]:
tensor = torch.tensor([9, 5, 7, 1, 2], dtype=torch.float32)
tensor
tensor.numel()

tensor([9., 5., 7., 1., 2.])

5

In [312]:
tensor.min()
tensor.max()
tensor.sum()

tensor(1.)

tensor(9.)

tensor(24.)

In [313]:
tensor.mean()
tensor.std()
tensor.var()

tensor(4.8000)

tensor(3.3466)

tensor(11.2000)

You can also do the same as above with `torch.min()`, etc. methods.

In [314]:
torch.min(tensor)
torch.max(tensor)
torch.sum(tensor)

tensor(1.)

tensor(9.)

tensor(24.)

Find the index of a tensor where the max or minimum occurs

In [315]:
tensor = torch.tensor([9, 5, 7, 1, 2])
tensor.argmax()
tensor.argmin()

tensor(0)

tensor(3)

# Matrix Multiplication

For matrices $A \in \mathbb{R}^{m \times n}$ and $B \in \mathbb{R}^{n \times p}$, the elements of the product $C = AB$ are given by:$$C_{ij} = \sum_{k=1}^{n} A_{ik} B_{kj}$$

**Explanation:**

$A$ is an $m \times n$ matrix (rows $\times$ columns).

$B$ is an $n \times p$ matrix.

The resulting matrix $C$ is $m \times p$.

To find the value at row $i$, column $j$ of the result, you perform a dot product of the $i$-th row of $A$ and the $j$-th column of $B$.

### Rules for Matrix Multiplication:

- The inner dimensions of the matrices must match for multiplication to be possible:

    Valid: (m, n) @ (n, p) → (m, p) ✓
    
    Invalid: (m, n) @ (k, p) where n ≠ k ✗

- The resulting matrix has the shape of the outer dimensions:

    (m, n) @ (n, p) → (m, p)

- Time complexity: O(mnp) for (m,n) @ (n,p)

In [316]:
tensor = torch.tensor([1, 2, 3])
torch.matmul(tensor, tensor)  # 1*1 + 2*2 + 3*3 = 14

tensor(14)

In [317]:
# Both are the same
torch.matmul(tensor, tensor)  # Prefer this
tensor @ tensor  # @ is matrix multiplication operator, not recommended

tensor(14)

tensor(14)

In [319]:
tensor1 = torch.tensor([
    [4, 5, 6],
    [1, 2, 1],
])  # 2x3

tensor2 = torch.tensor([
    [0, 0, 0, 2, 1],
    [0, 0, 0, 2, 1],
    [0, 0, 0, 2, 1],
])  # 3x5

tensor1.matmul(tensor2)  # 2x5

tensor([[ 0,  0,  0, 30, 15],
        [ 0,  0,  0,  8,  4]])

# Tensor Reshaping and Dimensionality Operations

* **`tensor.reshape(shape)`**:
  - Reshapes the tensor to the specified `shape` (if compatible). This is one of the most common ways to change tensor geometry.
  
* **`tensor.view(shape)`**:
  - Returns a different shape of the original tensor while sharing the same underlying data. Unlike reshape, it requires the tensor to be contiguous in memory.
  
* **`torch.stack(tensors, dim=0)`**:
  - Concatenates a sequence of tensors along a **new** dimension. Note that all tensors in the sequence must be the same size. (This remains a `torch` operation as it acts on multiple tensors).
  
* **`tensor.squeeze()`**:
  - Removes all dimensions of the tensor that have a size of **1**. For example, a tensor of shape `(5, 1, 10)` becomes `(5, 10)`.
  
* **`tensor.unsqueeze(dim)`**:
  - Adds a dimension with a size of **1** at the specified index `dim`. This is often used to add a "batch" dimension to a single data point.
  
* **`tensor.permute(dims)`**:
  - Returns a view of the original tensor with its dimensions rearranged according to the specified order.
  


In [321]:
# Create a base tensor for reshaping
x = torch.arange(1., 13.)
x
x.shape

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

torch.Size([12])

**1. Reshape**
   
Reshapes the tensor while keeping the same data. You get a new tensor of specified shape.

In [331]:
x_reshaped = x.reshape(4, 3)
x_reshaped
x_reshaped.shape  # Note: 4 * 3 = 12, so the total elements match.

tensor([[99.,  2.,  3.],
        [ 4.,  5.,  6.],
        [99.,  8.,  9.],
        [10., 11., 12.]])

torch.Size([4, 3])

**2. View**

Similar to reshape but acts as a direct "window" into the original memory.  
Changing `z` will change `x` because they share the same underlying data.

In [336]:
z = x.view(2, 6)
z[:, 0] = 99  # Changing z
z
x             # Notice x[0] is now 99.0 too

tensor([[99.,  2.,  3.,  4.,  5.,  6.],
        [99.,  8.,  9., 10., 11., 12.]])

tensor([99.,  2.,  3.,  4.,  5.,  6., 99.,  8.,  9., 10., 11., 12.])

**3. Squeeze**

Removes all dimensions with a value of 1.

In [347]:
# Create a tensor with extra "empty" dimensions
x_complex = x.reshape(1, 1, 12)
x_complex
print(f"Original shape: {x_complex.shape}")

x_squeezed = x_complex.squeeze()
x_squeezed
print(f"Squeezed shape: {x_squeezed.shape}")

tensor([[[99.,  2.,  3.,  4.,  5.,  6., 99.,  8.,  9., 10., 11., 12.]]])

Original shape: torch.Size([1, 1, 12])


tensor([99.,  2.,  3.,  4.,  5.,  6., 99.,  8.,  9., 10., 11., 12.])

Squeezed shape: torch.Size([12])


**4. Unsqueeze**

Adds a dimension of size 1 at a specific index.

In [348]:
# Let's add a dimension at index 0
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed
print(f"Unsqueezed at dim 0: {x_unsqueezed.shape}")

# Let's add a dimension at index 1
x_unsqueezed_1 = x_squeezed.unsqueeze(dim=1)
x_unsqueezed_1
print(f"Unsqueezed at dim 1: {x_unsqueezed_1.shape}")

tensor([[99.,  2.,  3.,  4.,  5.,  6., 99.,  8.,  9., 10., 11., 12.]])

Unsqueezed at dim 0: torch.Size([1, 12])


tensor([[99.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [99.],
        [ 8.],
        [ 9.],
        [10.],
        [11.],
        [12.]])

Unsqueezed at dim 1: torch.Size([12, 1])


**5. Permute**

Rearranges the order of the dimensions.  
Commonly used for changing Image formats (e.g., [Height, Width, Color] -> [Color, Height, Width]).

In [349]:
# Create a simulated image tensor: [Height, Width, Color_Channels]
x_image = torch.rand(size=(224, 224, 3))

# Permute to move Color_Channels to the first dimension: [Color, Height, Width]
x_permuted = x_image.permute(2, 0, 1)

print(f"Original shape: {x_image.shape}")
print(f"Permuted shape: {x_permuted.shape}")

Original shape: torch.Size([224, 224, 3])
Permuted shape: torch.Size([3, 224, 224])


**6. Stack**

Combines multiple tensors along a NEW dimension.

In [352]:
x_stack = torch.arange(1, 6)
x_stack

tensor([1, 2, 3, 4, 5])

In [354]:
# Stack them vertically (default dim=0)
v_stack = torch.stack([x_stack, x_stack, x_stack], dim=0)
v_stack
v_stack.shape

tensor([[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]])

torch.Size([3, 5])

In [355]:
# Stack them horizontally (dim=1)
h_stack = torch.stack([x_stack, x_stack, x_stack], dim=1)
h_stack
h_stack.shape

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4],
        [5, 5, 5]])

torch.Size([5, 3])

# Indexing

In [368]:
tensor = torch.tensor([
    [11, 12, 13],
    [21, 22, 23],
    [31, 32, 33],
])

tensor[0]
tensor[0][0]

tensor([11, 12, 13])

tensor(11)

In [377]:
tensor[:2]
tensor[:2, :2]

tensor([[11, 12, 13],
        [21, 22, 23]])

tensor([[11, 12],
        [21, 22]])

In [378]:
tensor[:2, 0]
tensor[:, 0]

tensor([11, 21])

tensor([11, 21, 31])

# PyTorch Tensors & NumPy

- `torch.from_numpy(numpy_array)` (array -> tensor)
- `tensor.numpy()` (tensor -> array)

In [381]:
torch.from_numpy(np.array([1, 2, 3]))

tensor([1, 2, 3])

In [382]:
tensor.numpy()

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

# Random seed

In [419]:
torch.manual_seed(seed=42)
torch.randint(1, 5, size=(2, 10))

tensor([[3, 4, 1, 3, 3, 4, 1, 1, 3, 2],
        [3, 3, 3, 3, 4, 1, 4, 4, 4, 3]])

# Getting PyTorch to run on the GPU