In [2]:
import numpy as np

In [15]:
def relu(Z):
  return np.maximum(0, Z)


def relu_backward(dA, Z):
  return np.where(Z > 0, dA, 0)


relu_backward(
    np.array([[0.1, 0.2], [-0.5, 2.1]]),
    np.array([[-5, 2], [1, -7]])
)

array([[ 0. ,  0.2],
       [-0.5,  0. ]])

In [23]:
def sigmoid(Z):
  return 1 / (1 + np.exp(-Z))


def sigmoid_backward(dA, Z):
  s = sigmoid(Z)
  return dA * s * (1 - s)


sigmoid(np.array([-5, -2, 2, 5]))

sigmoid_backward(
    np.array([-5, -2, 2, 5]),
    np.array([-1, 1, 0.5, -0.2]),
)

array([0.00669285, 0.11920292, 0.88079708, 0.99330715])

array([-0.98305967, -0.39322387,  0.47000742,  1.23758286])

In [55]:
def bce_loss(A2, y):
  A2 = np.clip(A2, 1e-9, (1 - 1e-9))
  loss = -np.mean(y*np.log(A2) + (1-y)*np.log(1-A2))
  return loss


def bce_loss_backward(A2, y):
  A2 = np.clip(A2, 1e-9, (1 - 1e-9))
  n = y.shape[0]
  return (-(y/A2) + (1-y)/(1-A2)) / n


bce_loss(
    A2=np.array([0.2, 0.55, 0.6, 0.1, 0.8]),
    y=np.array([0, 1, 1, 1, 0])
)

bce_loss(
    A2=np.array([0.2, 0.55, 0.6, 0.1, 0.8]),
    y=np.array([0, 1, 1, 0, 0])
)

np.float64(1.0487658362527934)

np.float64(0.6093209207855496)

In [138]:
A2 = np.array([0.2, 0.55, 0.6, 0.1, 0.8])
y = np.array([0, 1, 1, 1, 0])

In [139]:
bce_loss(A2, y)

lr = 0.01
dA2 = bce_loss_backward(A2, y)
A2 -= lr * dA2

np.float64(1.0487658362527934)