In [1]:
import numpy as np

The `np.c_` object in NumPy is a convenience utility for concatenating arrays along the second axis (columns).

It is used with slice notation `[]`, not with parentheses `()`. 

1. Combining two 1D arrays into a 2D array (as columns):

In [2]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

2. Converting a single 1D array into a column vector:

In [3]:
vec = np.arange(10)
np.c_[vec]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [4]:
X = np.array([
    [1, 2, 3],
    [5, 6, 7],
])  # BxM: 2x3

W = np.array([
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])  # MxN: 3x5

b = np.array([1, -1, 0, 2, 3])  # N: 5

X @ W
X @ W + b

array([[ 6, 12, 18, 24, 30],
       [18, 36, 54, 72, 90]])

array([[ 7, 11, 18, 26, 33],
       [19, 35, 54, 74, 93]])